### ISSUE TITLE
A mod to adjust character speed?

### ISSUE THREAD

**Issue by smidouni** [EVAST9919/touhosu#17]
Hello, I've been playing touhosu for a few weeks now but it's been really hard to find maps above 7* without using DT or other speed enhancing mods

That wouldn't be a problem usually but they also increase character speed quite a bit and make it really hard to dodge, so I was wondering if it'd be possible to add a mod to change character speed? Or maybe a variant of the DT mod but with regular character speed?

Sorry if this isn't formatted properly, I'm not very familiar with Github

**Comment by EVAST9919** [comment]
Added setting for speed adjustment mods to preserve player speed in the latest release
https://github.com/EVAST9919/touhosu/releases/tag/2024.1006.0
