### ISSUE TITLE
Discussion: Adjust determination zone of bullets

### ISSUE THREAD

**Issue by poly000** [EVAST9919/touhosu#4]
I just played taisei, then I found,
in taisei/touhou project, the determination zone of the bullets is only the center,
while in touhosu, it is the whole of the bullet.

https://user-images.githubusercontent.com/34085039/123495339-ed7eb380-d655-11eb-8320-28b3433b94af.mp4

**Comment by poly000** [comment]
Now in touhosu, some maps are very diffcult to FC...

**Comment by EVAST9919** [comment]
Fixed in [latest release](https://github.com/EVAST9919/touhosu/releases/tag/2021.628.0).
