### ISSUE TITLE
i am having an excruciating time trying to get touhousu to work 

### ISSUE THREAD

**Issue by ineedhelpwithtouhosu** [EVAST9919/touhosu#5]
i do not see any .dll files and do not know what to do

**Comment by EVAST9919** [comment]
All updates are happening [here](https://github.com/EVAST9919/touhosu/releases).
[Direct link to dll](https://github.com/EVAST9919/touhosu/releases/download/2021.628.0/osu.Game.Rulesets.Touhosu.dll) just for you <3
