### ISSUE TITLE
no directory

### ISSUE THREAD

**Issue by Githubadminstupide** [EVAST9919/touhosu#7]
<h1>I can't install it bc I can't find any osu related directory do I have to add the file in the zip installation file<h1/>

**Comment by EVAST9919** [comment]
When lazer is installed, you need to go to `%appdata%/osu/rulesets` (Windows) folder and place the .dll file into it.
You can find te latest .dll under latest release here: https://github.com/EVAST9919/touhosu/releases

**Comment by Githubadminstupide** [comment]
not a single osu related folder when i realize i try searching for map folder and the parameter file but nothing

**Comment by EVAST9919** [comment]
10 seconds search on youtube
https://www.youtube.com/watch?v=T5LbQWrpz_U&ab_channel=stayfunsteven
